name: hi aleks

'on':
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  say_hi:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "hi aleks :)"
